---
name: Russell
surname: Dinnage
position: "Research Fellow"
address: "Institute of Applied Ecology, University of Canberra"
phone: "+61 4 8155 4078"
www: www.mepheo.science
email: "r.dinnage@gmail.com"
twitter: ecologician
github: rdinnager
date: "`r format(Sys.time(), '%B %Y')`"
output: 
  vitae::moderncv:
    latex_engine: xelatex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
source("R/packages.R")
scholar_id <- "GU6p2KoAAAAJ"
orcid_id <- "0000-0003-0846-2819"
```

# Academic Positions

```{r pos}

positions <- orcid_employments(orcid_id)
positions[[1]]$`affiliation-group`$summaries %>%
  map_dfr(~tibble(start = paste(.x$`employment-summary.start-date.year.value` %||% "",
                               .x$`employment-summary.start-date.month.value` %||% "",
                               sep = "-"),
                  end = paste(.x$`employment-summary.end-date.year.value` %||% "",
                               .x$`employment-summary.end-date.month.value` %||% "",
                               sep = "-"),
                  what = .x$`employment-summary.role-title`,
                  where = paste0(ifelse(is.na(.x$`employment-summary.department-name`),
                                        "", paste0(.x$`employment-summary.department-name`,
                                                   ", ")),
                                 .x$`employment-summary.organization.name`),
                  city = paste0(.x$`employment-summary.organization.address.city`,
                                ", ", 
                                .x$`employment-summary.organization.address.country`))) %>%
  mutate(end = ifelse(end == "-", "present", end)) %>%
  detailed_entries(what = what,
                   when = glue("{start} - {end}"),
                   where = city,
                   with = where)


```

# Education

```{r edu}
ed <- orcid_educations(orcid_id)
ed[[1]]$`affiliation-group`$summaries %>%
  bind_rows() %>%
  brief_entries(what = `education-summary.role-title`,
                when = glue("{`education-summary.end-date.month.value`}-{`education-summary.end-date.year.value`}"),
                with = `education-summary.organization.name`)

```

# Publications (as of `r format(Sys.time(), '%B %Y')`)

```{r pubs}
works <- works(orcid_id) 
  
works <- works %>%
  as_tibble() %>%
  select(`title.title.value`, `journal-title.value`,
         `external-ids.external-id`) %>%
  dplyr::distinct(`title.title.value`, `journal-title.value`,
                  .keep_all = TRUE) %>%
  mutate(doi = map(`external-ids.external-id`, ~ .x %>%
                     filter(`external-id-type` == "doi") %>%
                     pull(`external-id-value`)) 
         ) %>%
  mutate(doi = modify_if(doi, ~ length(.x) == 0, ~NA_character_) %>%
           flatten_chr())

pubs <- get_publications(scholar_id) %>%
  dplyr::mutate(author = author %>% 
                  as.character %>% 
                  str_conv("UTF-8") %>%
                  str_trim(),
                type = dplyr::case_when(
                  journal == "bioRxiv" ~ "preprint",
                  journal == "University of Toronto" ~ "thesis",
                  journal == "" ~ "thesis",
                  TRUE ~ "peer-reviewed"
                  ),
                number = ifelse(number == "", "In Press", number)) %>%
  dplyr::arrange(dplyr::desc(year))

long_auth <- stringr::str_detect(pubs$author, "\\.\\.\\.")

pubs$author[long_auth] <- purrr::map_chr(pubs$pubid[long_auth], ~ get_complete_authors(scholar_id, .))
  
#pubs$title[!tolower(pubs$title) %in% tolower(works$title.title.value)]

pubs <- pubs %>%
  stringdist_left_join(works, by = c("title" = "title.title.value"))

dois <- na.omit(compact(pubs$doi))
alts <- map(dois,
            possibly(~altmetrics(doi = .x),
                     NULL)) %>%
  setNames(dois)

alt_scores <- compact(alts) %>%
  map_dbl("score")

pubs <- pubs %>%
  left_join(tibble(doi = names(alt_scores),
                   altmetric = alt_scores)) %>%
  mutate(altmetric = ifelse(is.na(altmetric),
                            0,
                            altmetric))

peer_reviewed <- pubs %>%
  filter(type == "peer-reviewed") %>% 
  distinct(title, .keep_all = TRUE) %>%
  mutate(pub_num = paste0(n():1, "."))

peer_reviewed %>%
  brief_entries(what = glue("{author} ({year}). {title}. \\textit{{{journal}}}. {number}. doi:{doi}"),
                when = pub_num,
                with = glue("\n{ifelse(cites > 0, paste0('\\\\textbf{Google Scholar Citations:} ', cites, '; '), '')}{ifelse(altmetric > 0, paste0('\\\\textbf{Altmetric Score:} ', altmetric, ';'), '')}"),
                .protect = FALSE)

```


* This CV is auto-generated using R once a week. See <https://github.com/rdinnager/CV> for the code.

