on:
  schedule:
    - cron: '17 1 * * 3'
  push:

jobs:
  build:
    runs-on: windows-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      ORCID_TOKEN: ${{ secrets.ORCID_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup R
        uses: r-lib/actions/setup-r@v1

      - name: Install pandoc
        uses: r-lib/actions/setup-pandoc@v1
          
      - name: Install dependencies (capsule)
        run: |
          install.packages("remotes")
          remotes::install_github("MilesMcBain/capsule")
        shell: Rscript {0}

      - name: Cache Renv packages
        uses: actions/cache@v2
        with:
          path: renv
          key: r-${{ hashFiles('renv.lock') }}
          restore-keys: r-
          
      - name: Try just restoring the renv
        run: |
          Rscript -e 'renv::restore()'
          
      - name: Render CV Rmarkdown file in capsule
        run: |
          tinytex::install_tinytex()
          tinytex::tlmgr_update()
          capsule::run_callr(function() rmarkdown::render("Russell_Dinnage_CV.Rmd"))  
        shell: Rscript {0}

      - name: Upload directory if failed
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: whole-directory
          path: .
      
      - name: Commit results
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git commit Russell_Dinnage_CV.pdf -m 'Re-build CV' || echo "No changes to commit"
          git push origin || echo "No changes to commit"

      - name: Upload CV pdf as artifact
        uses: actions/upload-artifact@v2
        with:
          name: RD_CV
          path: Russell_Dinnage_CV.pdf